apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pipeline22-ingress
  namespace: pipeline22
spec:
  ingressClassName: nginx
  rules:
  - host: 35.204.222.132.sslip.io
    http:
      paths:
      - backend:
          service:
            name: tree-app-service
            port:
              number: 8080
        path: /tree
        pathType: Prefix
status:
  loadBalancer: {}